language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - os: linux
      env: R_CODECOV=true
    - os: osx
      osx_image: xcode9.3

addons:
  apt:
    packages:
      - libpoppler-cpp-dev

r_github_packages:
  - jimhester/covr

warnings_are_errors: 1
#r_check_revdep: true

notifications:
  email:
    on_success: change
    on_failure: change

after_success:
  - if [[ "${R_CODECOV}" ]]; then R -e 'covr::codecov(type = "all")'; fi
